# -*- coding: utf-8 -*-
"""Graphs Of Various mathematical functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tL0VsLmhF8xgGuhT6nOzCZT-sbGHngmz
"""

# Commented out IPython magic to ensure Python compatibility.

#importing required libraries
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

#LINEAR
x = np.arange(-5.0, 5.0, 0.1)
y = 2*(x) + 3
y_noise = 2 * np.random.normal(size=x.size)
ydata = y + y_noise
#plt.figure(figsize=(8,6))
plt.plot(x, ydata,  'bo')
plt.plot(x,y, 'r')
plt.ylabel('Linear Dependent Variable')
plt.xlabel('Linear Independent Variable')
plt.show()

# CUBIC
x = np.arange(-5.0, 5.0, 0.1)
y = 1*(x**3) + 1*(x**2) + 1*x + 3
y_noise = 20 * np.random.normal(size=x.size)
ydata = y + y_noise
plt.plot(x, ydata,  'bo')
plt.plot(x,y, 'r')
plt.ylabel('Cubic Dependent Variable')
plt.xlabel('Cubic Independent Variable')
plt.show()

#QUADRATIC
x = np.arange(-5.0, 5.0, 0.1)
y = np.power(x,2)
y_noise = 2 * np.random.normal(size=x.size)
ydata = y + y_noise
plt.plot(x, ydata,  'bo')
plt.plot(x,y, 'r')
plt.ylabel('Quadratic Dependent Variable')
plt.xlabel('Quadratic Independent Variable')
plt.show()

#EXPONENTIAL
X = np.arange(-5.0, 5.0, 0.1)
Y= np.exp(X)
plt.plot(X,Y)
plt.ylabel('Exponential Dependent Variable')
plt.xlabel('Exponential Independent Variable')
plt.show()

#LOGARITHMIC
X = np.arange(-5.0, 5.0, 0.1)
Y = np.log(X)
plt.plot(X,Y)
plt.ylabel('Log Dependent Variable')
plt.xlabel('Log Independent Variable')
plt.show()

#SIGMODIAL/LOGISTIC
X = np.arange(-5.0, 5.0, 0.1)
Y = 1-4/(1+np.power(3, X-2))
plt.plot(X,Y)
plt.ylabel('Sig Dependent Variable')
plt.xlabel('Sig Independent Variable')
plt.show()