# -*- coding: utf-8 -*-
"""Linear Regression with Noise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5FDcaz2W1jDvSy4muyj3X_Y_Bjn60wZ
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
x = np.arange(-5.0,5.0,0.1)
y=2*(x)+3
y_noise=2*np.random.normal(size=x.shape)
plt.plot(x,y)
plt.plot(x,y_noise)
plt.xlabel('x')
plt.ylabel('y')
plt.figure(figsize=(8,6))
plt.plot(x,y)
ydata=y+y_noise
plt.plot(x,ydata)
plt.xlabel('INDEPENDENT VARIABLE')
plt.ylabel('DEPENDENT VARIABLE')
plt.show()
plt.plot(x ,y,label="Ideal Line")
plt.plot(x, y_noise,label="noise")
plt.legend()
plt.title("linear relationship with noise")
coffs = np.polyfit(x, ydata, 1)
m, b = coffs
y_pred = m*x+b
plt.figure(figsize=(8,6))
plt.plot(x, y_pred, label="Predicted Line")
plt.legend()
plt.title("Actual vs Predicted")
plt.show()

error = np.mean(ydata - y_pred)
print("Error: ", error)